ALTER TABLE items ADD COLUMN reorder_point INTEGER NOT NULL DEFAULT 0;
ALTER TABLE items ADD COLUMN safety_stock INTEGER NOT NULL DEFAULT 0;
ALTER TABLE items ADD COLUMN economic_order_qty INTEGER NOT NULL DEFAULT 0;
