CREATE TABLE IF NOT EXISTS permissions (
    id          TEXT PRIMARY KEY,
    code        TEXT NOT NULL UNIQUE,
    resource    TEXT NOT NULL,
    action      TEXT NOT NULL,
    description TEXT
);

INSERT OR IGNORE INTO permissions (id, code, resource, action, description) VALUES
    ('p1', 'iam:user:read', 'iam:user', 'read', 'Read users'),
    ('p2', 'iam:user:write', 'iam:user', 'write', 'Create/update users'),
    ('p3', 'iam:user:delete', 'iam:user', 'delete', 'Delete users'),
    ('p4', 'iam:role:read', 'iam:role', 'read', 'Read roles'),
    ('p5', 'iam:role:write', 'iam:role', 'write', 'Create/update roles'),
    ('p6', 'hcm:employee:read', 'hcm:employee', 'read', 'Read employees'),
    ('p7', 'hcm:employee:write', 'hcm:employee', 'write', 'Create/update employees'),
    ('p8', 'hcm:employee:delete', 'hcm:employee', 'delete', 'Terminate employees'),
    ('p9', 'hcm:payroll:read', 'hcm:payroll', 'read', 'Read payroll'),
    ('p10', 'hcm:payroll:write', 'hcm:payroll', 'write', 'Manage payroll'),
    ('p11', 'hcm:payroll:admin', 'hcm:payroll', 'admin', 'Administer payroll'),
    ('p12', 'hcm:department:read', 'hcm:department', 'read', 'Read departments'),
    ('p13', 'hcm:department:write', 'hcm:department', 'write', 'Create/update departments'),
    ('p14', 'erp:ledger:read', 'erp:ledger', 'read', 'Read general ledger'),
    ('p15', 'erp:ledger:write', 'erp:ledger', 'write', 'Create journal entries'),
    ('p16', 'erp:ledger:admin', 'erp:ledger', 'admin', 'Administer ledger'),
    ('p17', 'erp:ap:read', 'erp:ap', 'read', 'Read accounts payable'),
    ('p18', 'erp:ap:write', 'erp:ap', 'write', 'Manage AP'),
    ('p19', 'erp:ap:admin', 'erp:ap', 'admin', 'Administer AP'),
    ('p20', 'erp:ar:read', 'erp:ar', 'read', 'Read accounts receivable'),
    ('p21', 'erp:ar:write', 'erp:ar', 'write', 'Manage AR'),
    ('p22', 'erp:assets:read', 'erp:assets', 'read', 'Read fixed assets'),
    ('p23', 'erp:assets:write', 'erp:assets', 'write', 'Manage fixed assets'),
    ('p24', 'erp:cash:read', 'erp:cash', 'read', 'Read cash management'),
    ('p25', 'erp:cash:write', 'erp:cash', 'write', 'Manage cash'),
    ('p26', 'scm:inventory:read', 'scm:inventory', 'read', 'Read inventory'),
    ('p27', 'scm:inventory:write', 'scm:inventory', 'write', 'Manage inventory'),
    ('p28', 'scm:procurement:read', 'scm:procurement', 'read', 'Read procurement'),
    ('p29', 'scm:procurement:write', 'scm:procurement', 'write', 'Manage procurement'),
    ('p30', 'scm:procurement:admin', 'scm:procurement', 'admin', 'Administer procurement'),
    ('p31', 'scm:orders:read', 'scm:orders', 'read', 'Read orders'),
    ('p32', 'scm:orders:write', 'scm:orders', 'write', 'Manage orders'),
    ('p33', 'scm:manufacturing:read', 'scm:manufacturing', 'read', 'Read manufacturing'),
    ('p34', 'scm:manufacturing:write', 'scm:manufacturing', 'write', 'Manage manufacturing');
